import { createFileRoute } from "@tanstack/react-router"; import { motion,useReducedMotion } from "framer-motion"; import { competitions } from "../data/competitions"; import { workshops } from "../data/workshops"; import { history } from "../data/site"; import { Cta,Frame,SiteShell } from "../components/SiteShell"; import hero from "../assets/citadel-hero.jpg"; import arena from "../assets/arena-world.jpg"; import lab from "../assets/laboratory-world.jpg"; import powai from "../assets/powai-world.jpg";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Techfest IIT Bombay — An Aetherial Renaissance"},{name:"description",content:"Techfest IIT Bombay, 16–18 December 2026. Explore current competitions, workshops and initiatives."}]}),component:Home});
function Home(){const reduce=useReducedMotion();return <SiteShell><section className="home-hero"><motion.img initial={reduce?false:{scale:1.08}} animate={{scale:1}} transition={{duration:2}} src={hero} alt="Futuristic technology city rising around Powai"/><div className="hero-fog"/><div className="home-hud"/><motion.div className="home-copy" initial={reduce?false:{opacity:0,y:50}} animate={{opacity:1,y:0}} transition={{delay:.25,duration:.8}}><p className="eyebrow">IIT BOMBAY PRESENTS // 2026</p><h1>TECH<br/><span>FEST</span></h1><h2>AN AETHERIAL RENAISSANCE</h2><p className="hero-date">16 — 18 DECEMBER · IIT BOMBAY</p><p>Asia’s Largest Science &amp; Technology Festival</p><div><Cta to="/events">Explore Techfest</Cta><Cta to="/competitions">Enter competitions</Cta></div></motion.div><div className="hero-coords">19.1334° N<br/>72.9133° E<br/>MUMBAI NODE</div></section>
<section className="home-scale"><p className="eyebrow">CURRENT TRANSMISSION</p><h2>Build. Learn. <span>Compete.</span></h2><div className="scale-readouts"><Frame><b>{competitions.length}</b><span>Live competitions</span></Frame><Frame><b>{workshops.length}</b><span>Live workshops</span></Frame><Frame><b>1998</b><span>Founded</span></Frame><Frame><b>03</b><span>Festival days</span></Frame></div></section>
<section className="home-portals"><div className="section-copy"><p className="eyebrow">ACCESS THE WORLD</p><h2>Choose your frontier.</h2></div><div className="visual-portals"><Frame><img src={arena} alt="Technology arena" loading="lazy"/><div><small>01 // CYBER ARENA</small><h3>Competitions</h3><p>National challenges in drones, robotics, quantitative science and innovation.</p><Cta to="/competitions">View 15 challenges</Cta></div></Frame><Frame><img src={lab} alt="Future laboratory" loading="lazy"/><div><small>02 // FUTURE LAB</small><h3>Workshops</h3><p>Hands-on training across AI, engineering, design and technology.</p><Cta to="/workshops">View 25 workshops</Cta></div></Frame></div></section>
<section className="domain-ribbon"><p>AI</p><p>ROBOTICS</p><p>DRONES</p><p>SPACE</p><p>CYBERSECURITY</p><p>SUSTAINABILITY</p></section>
<section className="home-legacy"><div><p className="eyebrow">ARCHIVE SIGNAL</p><h2>A legacy of innovation.</h2><p>{history.at(-1)?.[1]}</p><Cta to="/history">Explore the archive</Cta></div><Frame><b>1998</b><span>—</span><b>2026</b><small>STUDENT-BUILT AT IIT BOMBAY</small></Frame></section>
<section className="home-location"><img src={powai} alt="IIT Bombay and Powai" loading="lazy"/><div><p className="eyebrow">ORIGIN NODE</p><h2>IIT BOMBAY</h2><p>Powai, Mumbai<br/>19.1334° N · 72.9133° E</p><Cta to="/about">Discover Techfest</Cta></div></section>
<section className="final-cta"><p className="eyebrow">THE SIGNAL IS LIVE</p><h2>THE FUTURE DOESN’T WAIT.<br/><span>BUILD IT.</span></h2><div><Cta to="/events">Enter Techfest</Cta><Cta to="/workshops">Join a workshop</Cta></div></section></SiteShell>}
